# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/work/download/c-sdk-6.2.5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/work/download/c-sdk-6.2.5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/work/download/c-sdk-6.2.5/CMakeFiles /data/work/download/c-sdk-6.2.5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/work/download/c-sdk-6.2.5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qiniu

# Build rule for target.
qiniu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qiniu
.PHONY : qiniu

# fast build rule for target.
qiniu/fast:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/build
.PHONY : qiniu/fast

# target to build an object file
b64/b64.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/b64/b64.o
.PHONY : b64/b64.o

# target to preprocess a source file
b64/b64.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/b64/b64.i
.PHONY : b64/b64.i

# target to generate assembly for a file
b64/b64.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/b64/b64.s
.PHONY : b64/b64.s

# target to build an object file
b64/urlsafe_b64.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/b64/urlsafe_b64.o
.PHONY : b64/urlsafe_b64.o

# target to preprocess a source file
b64/urlsafe_b64.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/b64/urlsafe_b64.i
.PHONY : b64/urlsafe_b64.i

# target to generate assembly for a file
b64/urlsafe_b64.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/b64/urlsafe_b64.s
.PHONY : b64/urlsafe_b64.s

# target to build an object file
cJSON/cJSON.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/cJSON/cJSON.o
.PHONY : cJSON/cJSON.o

# target to preprocess a source file
cJSON/cJSON.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/cJSON/cJSON.i
.PHONY : cJSON/cJSON.i

# target to generate assembly for a file
cJSON/cJSON.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/cJSON/cJSON.s
.PHONY : cJSON/cJSON.s

# target to build an object file
qiniu/auth_mac.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/auth_mac.o
.PHONY : qiniu/auth_mac.o

# target to preprocess a source file
qiniu/auth_mac.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/auth_mac.i
.PHONY : qiniu/auth_mac.i

# target to generate assembly for a file
qiniu/auth_mac.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/auth_mac.s
.PHONY : qiniu/auth_mac.s

# target to build an object file
qiniu/base.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/base.o
.PHONY : qiniu/base.o

# target to preprocess a source file
qiniu/base.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/base.i
.PHONY : qiniu/base.i

# target to generate assembly for a file
qiniu/base.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/base.s
.PHONY : qiniu/base.s

# target to build an object file
qiniu/base_io.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/base_io.o
.PHONY : qiniu/base_io.o

# target to preprocess a source file
qiniu/base_io.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/base_io.i
.PHONY : qiniu/base_io.i

# target to generate assembly for a file
qiniu/base_io.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/base_io.s
.PHONY : qiniu/base_io.s

# target to build an object file
qiniu/conf.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/conf.o
.PHONY : qiniu/conf.o

# target to preprocess a source file
qiniu/conf.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/conf.i
.PHONY : qiniu/conf.i

# target to generate assembly for a file
qiniu/conf.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/conf.s
.PHONY : qiniu/conf.s

# target to build an object file
qiniu/http.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/http.o
.PHONY : qiniu/http.o

# target to preprocess a source file
qiniu/http.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/http.i
.PHONY : qiniu/http.i

# target to generate assembly for a file
qiniu/http.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/http.s
.PHONY : qiniu/http.s

# target to build an object file
qiniu/io.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/io.o
.PHONY : qiniu/io.o

# target to preprocess a source file
qiniu/io.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/io.i
.PHONY : qiniu/io.i

# target to generate assembly for a file
qiniu/io.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/io.s
.PHONY : qiniu/io.s

# target to build an object file
qiniu/resumable_io.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/resumable_io.o
.PHONY : qiniu/resumable_io.o

# target to preprocess a source file
qiniu/resumable_io.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/resumable_io.i
.PHONY : qiniu/resumable_io.i

# target to generate assembly for a file
qiniu/resumable_io.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/resumable_io.s
.PHONY : qiniu/resumable_io.s

# target to build an object file
qiniu/rs.o:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/rs.o
.PHONY : qiniu/rs.o

# target to preprocess a source file
qiniu/rs.i:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/rs.i
.PHONY : qiniu/rs.i

# target to generate assembly for a file
qiniu/rs.s:
	$(MAKE) -f CMakeFiles/qiniu.dir/build.make CMakeFiles/qiniu.dir/qiniu/rs.s
.PHONY : qiniu/rs.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... qiniu"
	@echo "... rebuild_cache"
	@echo "... b64/b64.o"
	@echo "... b64/b64.i"
	@echo "... b64/b64.s"
	@echo "... b64/urlsafe_b64.o"
	@echo "... b64/urlsafe_b64.i"
	@echo "... b64/urlsafe_b64.s"
	@echo "... cJSON/cJSON.o"
	@echo "... cJSON/cJSON.i"
	@echo "... cJSON/cJSON.s"
	@echo "... qiniu/auth_mac.o"
	@echo "... qiniu/auth_mac.i"
	@echo "... qiniu/auth_mac.s"
	@echo "... qiniu/base.o"
	@echo "... qiniu/base.i"
	@echo "... qiniu/base.s"
	@echo "... qiniu/base_io.o"
	@echo "... qiniu/base_io.i"
	@echo "... qiniu/base_io.s"
	@echo "... qiniu/conf.o"
	@echo "... qiniu/conf.i"
	@echo "... qiniu/conf.s"
	@echo "... qiniu/http.o"
	@echo "... qiniu/http.i"
	@echo "... qiniu/http.s"
	@echo "... qiniu/io.o"
	@echo "... qiniu/io.i"
	@echo "... qiniu/io.s"
	@echo "... qiniu/resumable_io.o"
	@echo "... qiniu/resumable_io.i"
	@echo "... qiniu/resumable_io.s"
	@echo "... qiniu/rs.o"
	@echo "... qiniu/rs.i"
	@echo "... qiniu/rs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

